server:
    port: 7002
eureka:
    instance:
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://user:user@peer1:9001/eureka/
spring:
    application:
        #应用名称
        name: config-server
    profiles:
        active: dev   #开发环境
    boot:  
        admin:  
            client:  
                prefer-ip: true # 解决windows下运行时无法识别主机名的问题  
            url: http://localhost:10000/aicloud-monitor # 向服务端注册的地址
    cloud:
        config:
            server:
                git:
                    #配置中心配置资源地址
                    uri: https://github.com/Johnnyzhoutq/eureka-ribbon-hystrix-zuul
                    #配置中心配置资源搜寻路径
                    searchPaths: config-repo
                    username: johnnyzhoutq@gmail.com
                    password: xxxxxxxx