server:
    port: 9000

spring:
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true

aicloud:
    datasource:
        datasourceName: defaultDatasource
        url: jdbc:mysql://localhost:3306/aicloud-boot-test
        username: root
        password: root
    datasources:
        - datasourceName: myDatasource1
          url: jdbc:mysql://localhost:3306/aicloud-boot-test1
          username: root
          password: root