spring:
    application:
        name: aicloud-eureka-server
server:
    port: 9002
eureka:
    instance:
        prefer-ip-address: false
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        #delete this if only one eureka server
        hostname: peer2
    server:
        enable-self-preservation: false
    client:
        register-with-eureka: true
        #是否需要去检索寻找服务，默认是true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://peer1:9001/eureka/
